name: tsn-analyzer
channels:
  - defaults
  - conda-forge
dependencies:
  - amply=0.1.5
  - blas=1.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2022.10.11
  - certifi=2022.9.24
  - coincbc=2.10.5
  - cycler=0.11.0
  - docutils=0.18.1
  - fonttools=4.25.0
  - freetype=2.12.1
  - giflib=5.2.1
  - intel-openmp=2021.4.0
  - jpeg=9e
  - kiwisolver=1.4.2
  - lcms2=2.12
  - lerc=3.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcxx=14.0.6
  - libdeflate=1.8
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - liblapack=3.9.0
  - libpng=1.6.37
  - libtiff=4.4.0
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - llvm-openmp=14.0.6
  - lz4-c=1.9.3
  - matplotlib=3.5.3
  - matplotlib-base=3.5.3
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - munkres=1.1.4
  - ncurses=6.3
  - networkx=2.8.4
  - numpy=1.23.4
  - numpy-base=1.23.4
  - openssl=1.1.1s
  - packaging=21.3
  - pillow=9.2.0
  - pip=22.2.2
  - pulp=2.7.0
  - pyparsing=3.0.9
  - python=3.10.8
  - python-dateutil=2.8.2
  - python_abi=3.10
  - readline=8.2
  - setuptools=65.5.0
  - six=1.16.0
  - sqlite=3.40.0
  - tk=8.6.12
  - tornado=6.2
  - tzdata=2022f
  - wheel=0.37.1
  - xz=5.2.6
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
    - mdutils==1.4.0
